### ISSUE TITLE
error with timestamps when creating new ToDo

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#128]
Found in #116 
```

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building StreamBuilder<dynamic>(dirty, state: _StreamBuilderBaseState<dynamic, AsyncSnapshot<dynamic>>#b0530):
type 'Timestamp' is not a subtype of type 'num' of 'other'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was
    MaintenanceHistory 
lib/screens/homescreen.dart:54
When the exception was thrown, this was the stack
#0      int.compareTo (dart:core-patch/integers.dart)
#1      TodoBLoC.sortItems.<anonymous closure> 
package:autodo/blocs/todo.dart:43
#2      Sort._insertionSort  (dart:_internal/sort.dart:69:36)
#3      Sort._doSort  (dart:_internal/sort.dart:58:7)
#4      Sort.sort  (dart:_internal/sort.dart:33:5)
...
═══════════════════════════════════
```

**Comment by baylessj** [comment]
A fix is incoming for this, but it puts the todo item with a date at the bottom of the queue when there isn't sufficient driving data available to make dueDates from dueMileages. I think the long-term solution for that will be to set a typical default driving rate, and then update it based on the user's habits.
