### ISSUE TITLE
Error loading json_intl assets on app launch

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#252]
I'm greeted by an uncaught exception when trying to start the app on the latest version from develop:

```
I/flutter (25420): Language file not found assets/intl/strings-en.json                                             
I/flutter (25420): Transition: Transition { currentState: Uninitialized, event: AppStarted { integrationTest: false }, nextState: LocalAuthenticated { newUser: false } }
I/flutter (25420):                                                                                                 
I/flutter (25420): Event: TrialLogin { newUser: false }                                                            
I/flutter (25420):                                                                                                 
I/flutter (25420): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25420): The following assertion was thrown building Builder(dirty, dependencies:                        
I/flutter (25420): [_LocalizationsScope-[GlobalKey#626f0]]):                                                       
I/flutter (25420): The key app_title was not found                                                                 
I/flutter (25420): 'package:json_intl/src/json_intl_data.dart':                                                    
I/flutter (25420): Failed assertion: line 35 pos 12: '_localizedValues.keys.contains(key)'                         
I/flutter (25420):                                                                                                 
I/flutter (25420): The relevant error-causing widget was:                                                          
I/flutter (25420):   MaterialApp file:///home/bayle/Documents/git/autodo/lib/main.dart:160:12                      
I/flutter (25420):                                                                                                 
I/flutter (25420): When the exception was thrown, this was the stack:                                              
I/flutter (25420): #2      JsonIntlData.translate (package:json_intl/src/json_intl_data.dart:35:12)                
I/flutter (25420): #3      JsonIntl.get (package:json_intl/src/json_intl.dart:42:20)                               
I/flutter (25420): #4      App.build.<anonymous closure> (package:autodo/main.dart:162:32)                         
I/flutter (25420): #5      _WidgetsAppState.build.<anonymous closure> (package:flutter/src/widgets/app.dart:1371:39)
I/flutter (25420): #6      Builder.build (package:flutter/src/widgets/basic.dart:6995:41)                          
I/flutter (25420): #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:4547:28)             
I/flutter (25420): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4478:15)    
I/flutter (25420): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4202:5)                     
I/flutter (25420): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4461:5)        
I/flutter (25420): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4456:5)              
I/flutter (25420): ...     Normal element mounting (16 frames)                                                     
I/flutter (25420): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3430:14)              
I/flutter (25420): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3195:20)                
I/flutter (25420): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4498:16)    
I/flutter (25420): #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4646:11)     
I/flutter (25420): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4202:5)                     
I/flutter (25420): #32     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2611:33)              
I/flutter (25420): #33     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)              
I/flutter (25420): #34     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (25420): #35     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
I/flutter (25420): #36     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)    
I/flutter (25420): #37     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:856:7)
I/flutter (25420): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (25420):                                                                                                 
I/flutter (25420): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by DavBfr** [comment]
Closed by #256
